### ISSUE TITLE
Advanced SysMessage macro

### ISSUE THREAD

**Issue by jonlinper** [msturgill/razor#6]
Hi,

I'm working in a macro and trying to distinguish sysmessage "2" from "Lord British: 2".
Seems not possible, and I'm thinking on modifying the source code and re-build Razor.

1. Any idea of how to distinguish it just using macro code?
2. If re-build inevitable, there is any documentation of how to compile the project?

Thank you.

**Comment by markdwags** [comment]
I'm on the same boat as you, I'd love to make some enhancements to the macro management of Razor but my understanding is that you cannot build Razor for redistribution because the Crypt and Loader code isn't available.

And I'm fine with that. I don't want to redistribute my own version, just update the main version to make the UI experience around macroing but I've had a hell of a time trying to get this project to run, ultimately I cannot get past the Crypt.dll version error. I'm hoping @msturgill can provide some guidance.

[This project](https://github.com/jaedan/razor) got me farther, it has the source code for those but when I run it I get errors about reading memory.  I can bypass them in debug mode but Razor then doesn't communicate with UO and not much works. Perhaps @jaedan could help?

Thanks,
Mark

**Comment by jonlinper** [comment]
Thanks for reponse, @markdwags.

@jaedan project seems great, I'll try to compile it and tell you if it works.

**Comment by markdwags** [comment]
I'm curious what you find @jonlinper -- if you can get past this error I'd be very excited.  

> System.AccessViolationException: 'Attempted to read or write protected memory. This is often an indication that other memory is corrupt.'

**Comment by jaedan** [comment]
Last I checked my fork just works - I certainly use a version of razor I built myself. Did you try running as administrator? It looks like you're getting a permission error.

**Comment by markdwags** [comment]
Thanks @jaedan -- I tried that but no luck.  I wonder what's different on my end.

It pops up all over, but hits line 810 in ClientComm.cs first.

`(InitError)InstallLibrary( mainWindow, ClientProc.Id, flags );`

```
System.AccessViolationException occurred
  HResult=0x80004003
  Message=Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
  Source=<Cannot evaluate the exception source>
  StackTrace:
   at Assistant.ClientCommunication.InstallLibrary(IntPtr thisWnd, Int32 procid, Int32 features)
   at Assistant.ClientCommunication.InstallHooks(IntPtr mainWindow) in E:\Programming\razor-VS2017\Razor\Network\ClientComm.cs:line 810
   at Assistant.Razor.Razor_Load(Object sender, EventArgs e) in E:\Programming\razor-VS2017\Razor\UI\Razor.cs:line 2756
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at Assistant.Razor.WndProc(Message& msg) in E:\Programming\razor-VS2017\Razor\UI\Razor.cs:line 2728
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.DebuggableCallback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

```

Any luck @jonlinper ?
